---
parameters:
  - name: environmentName
    type: string
  - name: serviceConnection
    type: string

jobs:
  - deployment: deploy_adf
    displayName: 'Deploy to Azure Data Factory'
    pool:
      vmImage: 'windows-2019'
    environment: ${{ parameters.environmentName }}
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: mdwdataops_adfpublish
              path: 'adf_publish'

            # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell
            - task: AzurePowerShell@4
              displayName: 'Azure PowerShell script: Stop ADF triggers'
              inputs:
                azureSubscription: ${{ parameters.serviceConnection }}
                ScriptPath: '$(Pipeline.Workspace)/ciartifacts/adf_scripts/deploymentadf.ps1'
                ScriptArguments: '-armTemplate "$(Pipeline.Workspace)\adf_publish\$(devAdfName)\ARMTemplateForFactory.json" -ResourceGroupName "$(rgName)" -DataFactoryName "$(adfName)" -predeployment $true'
                azurePowerShellVersion: LatestVersion

            # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment
            - task: AzureResourceGroupDeployment@2
              displayName: 'Azure Deployment:Create Or Update Resource Group action on $(rgName)'
              inputs:
                azureSubscription: ${{ parameters.serviceConnection }}
                resourceGroupName: '$(rgName)'
                location: '$(azureLocation)'
                csmFile: '$(Pipeline.Workspace)/adf_publish/$(devAdfName)/ARMTemplateForFactory.json'
                csmParametersFile: '$(Pipeline.Workspace)/adf_publish/$(devAdfName)/ARMTemplateParametersForFactory.json'
                overrideParameters: -factoryName "$(adfName)" -DataLakeStorage_properties_typeProperties_url "https://$(datalakeAccountName).dfs.core.windows.net/" -KeyVault_properties_typeProperties_baseUrl "$(kvUrl)" -SourceDataStorage_properties_typeProperties_url "https://$(fileshareAccountName).dfs.core.windows.net/"

            # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell
            - task: AzurePowerShell@4
              displayName: 'Azure PowerShell script: Start ADF triggers'
              inputs:
                azureSubscription: ${{ parameters.serviceConnection }}
                ScriptPath: '$(Pipeline.Workspace)/ciartifacts/adf_scripts/deploymentadf.ps1'
                ScriptArguments: '-armTemplate "$(Pipeline.Workspace)\adf_publish\$(devAdfName)\ARMTemplateForFactory.json" -ResourceGroupName "$(rgName)" -DataFactoryName "$(adfName)" -predeployment $false'
                azurePowerShellVersion: LatestVersion
