trigger:
  branches:
    include:
    - main
    - release/*
    - e2e/temperature-events-milestone1
  paths:
    include:
    - e2e_samples/temperature_events/*

variables:
  basePath: 'e2e_samples/temperature_events'
  azfuncPath: '$(basePath)/Functions'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: LintCheck
  displayName: 'Lint Check'
  jobs:
  - job: CSharpLintCheck
    steps:
    - script: 'dotnet tool restore'
      workingDirectory: $(azfuncPath)
      displayName: 'Lint tool restore from nuget'
    - script: 'dotnet tool run dotnet-format -- --check'
      workingDirectory: $(azfuncPath)
      displayName: 'Lint C# code'

- stage: BuildAndPublish
  displayName: 'Build and publish as artifact in Azure DevOps'
  jobs:
  - job: Build
    steps:
    - script: 'dotnet restore'
      displayName: 'restore nuget packages'
      workingDirectory: $(azfuncPath)
    - script: 'dotnet build --output publish_output --configuration Release'
      displayName: 'build artifact'
      workingDirectory: $(azfuncPath)
    # Need to publish code coverage report
    - script: 'dotnet test'
      displayName: 'test code'
      workingDirectory: $(azfuncPath)
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(azfuncPath)/publish_output/'
        includeRootFolder: false
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)
        artifactName: 'drop'
