

trigger: none

pr: none

resources:
  pipelines:
  - pipeline: ci
    source: mdw-dbx-nd-ci-pipeline
    # trigger: 
    #   branches:
    #   - master

stages:
- stage: deploy_to_test
  displayName: 'Deploy notebooks'
  variables:
  - group: mdwdo-dbx-nd-test
  jobs:
  - template: ../../devops/templates/jobs/deploy-notebooks-job.yml
    parameters:
      environmentName: 'TEST'
      databricksDomain: '$(databricksDomain)'
      databricksToken: '$(databricksToken)'
      databricksNotebookPath: '$(databricksNotebookPath)'
      databricksLocalNotebookPath: $(Pipeline.Workspace)/ci/notebooks
  - template: ../../devops/templates/jobs/integration-tests-job.yml
    parameters:
      environmentName: 'TEST'
      databricksDomain: '$(databricksDomain)'
      databricksToken: '$(databricksToken)'
      databricksNotebookPath: '$(databricksNotebookPath)'
      databricksTestsNotebookPath: $(Pipeline.Workspace)/ci/notebooks/tests
      databricksClusterId: '$(databricksClusterId)'
      devopsScriptsBasePath: $(Pipeline.Workspace)/ci/devops_scripts