version: 2
updates:
  - package-ecosystem: "pip"
    directories:
      - "/fabric/*"
      - "/databricks/*"
      - "/azuredatafactory/*"
      - "/azuresqldb/*"
    schedule:
      interval: "weekly"
    exclude-paths:
      - "/archive/**"
  - package-ecosystem: "npm"
    directories:
      - "/fabric/*"
      - "/databricks/*"
      - "/azuredatafactory/*"
      - "/azuresqldb/*"
    schedule:
      interval: "weekly"
    exclude-paths:
      - "/archive/**"
