# Nutter pipeline for SparkSQL Tests

trigger:
  branches:
    include:
    - single-tech/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.5'

- task: configuredatabricks@0
  displayName: 'Configure Databricks CLI'
  inputs:
    url: $(databricks_host)
    token: $(databricks_token)

- task: deploynotebooks@0
  displayName: 'Publish notebooks to test workspace'
  inputs:
    notebooksFolderPath: $(notebook_folder_path)
    workspaceFolder: $(workspace_folder)

- script: |
    pip install nutter
  displayName: 'Install Nutter'

- script: |
    nutter run $SEARCHFOLDER $CLUSTER --recursive --junit_report
  displayName: 'Execute Nutter'
  env:
      SEARCHFOLDER: $(test_search_folder)
      CLUSTER: $(clusterID)
      DATABRICKS_HOST: $(databricks_host)
      DATABRICKS_TOKEN: $(databricks_token)

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/test-*.xml'
    testRunTitle: 'Publish Nutter results'
  condition: succeededOrFailed()