trigger: none

pr: none

resources:
  pipelines:
  - pipeline: ciartifacts
    source: mdwdops-ci-artifacts
    trigger: 
      branches:
      - main
  repositories:
  - repository: mdwdataops_workspace_publish
    type: github
    endpoint: mdwdops-github
    name: your_github_handle/your_repo  # deploy script should replace this with your github repo
    ref: workspace_publish

stages:
- stage: deploy_to_dev
  displayName: 'Deploy to DEV'  # In DEV, excludes publishing to Synapse workspace as this is a manual publish step
  variables:
  - group: mdwdops-release-dev
  - group: mdwdops-secrets-dev
  jobs:
  - template: templates/jobs/deploy-dedicated-sql-pool-job.yml
    parameters:
      environmentName: 'DEV'
      serviceConnection: 'mdwdops-serviceconnection-dev'
  - template: templates/jobs/deploy-wheel-job.yml
    parameters:
      environmentName: 'DEV'
      serviceConnection: 'mdwdops-serviceconnection-dev'

- stage: deploy_to_stg
  displayName: 'Deploy to Stage'
  variables:
  - group: mdwdops-release-stg
  - group: mdwdops-secrets-stg
  jobs: 
  - template: templates/jobs/deploy-dedicated-sql-pool-job.yml
    parameters:
      environmentName: 'STG'
      serviceConnection: 'mdwdops-serviceconnection-stg'
  - template: templates/jobs/deploy-wheel-job.yml
    parameters:
      environmentName: 'STG'
      serviceConnection: 'mdwdops-serviceconnection-stg'
  - template: templates/jobs/deploy-synapse-workspace-job.yml
    parameters:
      environmentName: 'STG'
      serviceConnection: 'mdwdops-serviceconnection-stg'
  # Integration tests
  - template: templates/jobs/integration-tests-job.yml

- stage: deploy_to_prod
  displayName: 'Deploy to Prod'
  variables:
  - group: mdwdops-release-prod
  - group: mdwdops-secrets-prod
  jobs: 
  - template: templates/jobs/deploy-dedicated-sql-pool-job.yml
    parameters:
      environmentName: 'PROD'
      serviceConnection: 'mdwdops-serviceconnection-prod'
  - template: templates/jobs/deploy-wheel-job.yml
    parameters:
      environmentName: 'PROD'
      serviceConnection: 'mdwdops-serviceconnection-prod'
  - template: templates/jobs/deploy-synapse-workspace-job.yml
    parameters:
      environmentName: 'PROD'
      serviceConnection: 'mdwdops-serviceconnection-prod'