variables:
- group: Databricks-dev-environment
- group: Databricks-stg-environment
- group: Databricks-prod-environment


trigger:
  batch: true
  branches:
    include:
    - '*'

  tags:
    include:
      - v*.*
      - prod

  paths:
    include:
      - common/**

stages:


- stage: test_at_stg
  displayName: 'Test at Staging'
  condition: |
      or(
        startsWith(variables['Build.SourceBranch'], 'refs/heads/staging'),
        startsWith(variables['Build.SourceBranch'], 'refs/heads/production')
      )
  jobs:
  - template: ./template/test-lib-job.yml
    parameters:
      environmentName: 'STG'  
  - template: ./template/deploy-lib-job.yml
    parameters:
      environmentName: 'STG'
      databricksDomain: '$(databricksDomain_stg)'
      databricksToken: '$(databricksToken_stg)'
      databricksClusterId: '$(databricksClusterId_stg)'
  - template: ./template/deploy-notebook-job.yml
    parameters:
      environmentName: 'STG'
      databricksDomain: '$(databricksDomain_stg)'
      databricksToken: '$(databricksToken_stg)'
      databricksNotebookPath: '/Shared/notebook-tests/dbxbuild_$(Build.BuildId)/'
  - template: ./template/test-notebook-job.yml
    parameters:
      environmentName: 'STG'
      databricksDomain: '$(databricksDomain_stg)'
      databricksToken: '$(databricksToken_stg)'
      databricksClusterId: '$(databricksClusterId_stg)'
      databricksNotebookPath: '/Shared/notebook-tests/dbxbuild_$(Build.BuildId)/'


- stage: deploy_to_prod
  displayName: 'Deploy to Prod'
  condition: |
    and(
      startsWith(variables['Build.SourceBranch'], 'refs/heads/production'),
      succeeded('test_at_stg')
    )
  jobs:
  - template: ./template/test-lib-job.yml
    parameters:
      environmentName: 'PROD' 
  - template: ./template/deploy-lib-job.yml
    parameters:
      environmentName: 'PROD'
      databricksDomain: '$(databricksDomain_prod)'
      databricksToken: '$(databricksToken_prod)'
      databricksClusterId: '$(databricksClusterId_prod)'
  - template: ./template/deploy-notebook-job.yml
    parameters:
      environmentName: 'PROD'
      databricksDomain: '$(databricksDomain_prod)'
      databricksToken: '$(databricksToken_prod)'
      databricksNotebookPath: '/Shared/notebooks-release/'