---
trigger: none

pr: none

resources:
  pipelines:
    - pipeline: ciartifacts
      source: mdwdo-adf-ci-artifacts
      trigger:
        branches:
          - main
  repositories:
    - repository: mdwdataops_adfpublish
      type: github
      endpoint: mdwdo-adf-github
      name: githubuser/mdw-dataops-clone
      ref: adf_publish

# The deployment script sets this as a Pipeline Variable, but you may choose to set it here in the definition
#
# variables:
#   devAdfName: <DEV DATAFACTORY NAME>

stages:
  - stage: deploy_to_stg
    displayName: 'Deploy to Stage'
    variables:
      - group: mdwdo-adf-release-stg
      - group: mdwdo-adf-release-secrets-stg
    jobs:
      - template: templates/jobs/deploy-adf-job.yml
        parameters:
          environmentName: 'STG'
          serviceConnection: 'mdwdo-adf-serviceconnection-stg'
      - template: templates/jobs/integration-test-adf-job.yml
        parameters:
          environmentName: 'STG'
          serviceConnection: 'mdwdo-adf-serviceconnection-stg'
          resourceGroup: $(rgName)
          datafactoryName: $(adfName)
          accountName: $(datalakeAccountName)
          accountKey: $(datalakeKey)

  - stage: deploy_to_prod
    displayName: 'Deploy to Prod'
    variables:
      - group: mdwdo-adf-release-prod
      - group: mdwdo-adf-release-secrets-prod
    jobs:
      - template: templates/jobs/deploy-adf-job.yml
        parameters:
          environmentName: 'PROD'
          serviceConnection: 'mdwdo-adf-serviceconnection-prod'
