trigger:
- main

pr: none

variables:
  SLN_NAME: 'ddo_samples_azuresql'
  SLN_DIR: 'single_tech_samples\azuresql\src\$(SLN_NAME)'
  SLN: '$(SLN_DIR)\$(SLN_NAME).sln'
  BUILD_PLATFORM: 'any cpu'
  BUILD_CONFIGURATION: 'release'
  AZURESQL_FULL_SERVER_NAME: '$(AZURESQL_SERVER_NAME).database.windows.net'
  AZURESQL_RESTORED_DB_NAME: 'salesdb_test_$(Build.BuildNumber)'

stages:
- stage: 'build'
  displayName: 'Build'
  jobs:
  - job: 'build_sql_dacpac'
    displayName: 'Build SQL DACPAC'
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: NuGetToolInstaller@1
      displayName: 'Install Nuget'
    - task: NuGetCommand@2
      displayName: 'Restore Nuget packages'
      inputs:
        restoreSolution: '$(SLN)'
    - task: VSBuild@1
      displayName: 'Build solution sln'
      inputs:
        solution: '$(SLN)'
        platform: '$(BUILD_PLATFORM)'
        configuration: '$(BUILD_CONFIGURATION)'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(SLN_DIR)\$(SLN_NAME)\bin\$(BUILD_CONFIGURATION)\$(SLN_NAME).dacpac' # wildcards(*) are not supported
        artifact: 'sql_dacpac'
        publishLocation: 'pipeline'

- stage: 'restore_and_deploy_to_test'
  displayName: 'Test'
  jobs:
  - job: 'restore_prod_to_test'
    displayName: 'Restore prod to test'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'mdwdo-azsql'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          restore_timeformat=$(date --rfc-3339=seconds | sed -e 's/ /T/')
          az sql db restore \
              --dest-name $(AZURESQL_RESTORED_DB_NAME) \
              --edition GeneralPurpose \
              --name $(AZURESQL_DB_NAME) \
              --resource-group $(RESOURCE_GROUP_NAME) \
              --server $(AZURESQL_SERVER_NAME) \
              --time $restore_timeformat
  - job: 'deploy_to_test'
    displayName: 'Deploy to test'
    dependsOn: 'restore_prod_to_test'
    condition: succeeded('restore_prod_to_test')
    pool:
      vmImage: 'windows-latest'
    steps:
    - download: current
      artifact: 'sql_dacpac'
    - task: AzureKeyVault@1
      inputs:
        azureSubscription: 'mdwdo-azsql'
        KeyVaultName: '$(AZURE_KEYVAULT_NAME)'
        SecretsFilter: '*'
    - task: SqlAzureDacpacDeployment@1
      inputs:
        azureSubscription: 'mdwdo-azsql'
        AuthenticationType: 'server'
        ServerName: '$(AZURESQL_FULL_SERVER_NAME)'
        DatabaseName: '$(AZURESQL_RESTORED_DB_NAME)'
        SqlUsername: '$(AZURESQL_SERVER_USERNAME)'
        SqlPassword: '$(AZURESQL-SERVER-KEYVAULT-PASSWORD)'
        deployType: 'DacpacTask'
        DeploymentAction: 'Publish'
        DacpacFile: '$(Pipeline.Workspace)\sql_dacpac\$(SLN_NAME).dacpac'
        IpDetectionMethod: 'AutoDetect'
  - job: 'teardown_test'
    dependsOn: 'deploy_to_test'
    condition: always()
    displayName: 'Teardown Test'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'mdwdo-azsql'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az sql db delete \
              --name $(AZURESQL_RESTORED_DB_NAME) \
              --resource-group $(RESOURCE_GROUP_NAME) \
              --server $(AZURESQL_SERVER_NAME) \
              --yes

- stage: 'deploy_to_prod'
  displayName: 'Prod'
  jobs:
  - job: 'deploy_sql_dacpac'
    displayName: 'Deploy SQL DACPAC'
    pool:
      vmImage: 'windows-latest'
    steps:
    - download: current
      artifact: 'sql_dacpac'
    - task: AzureKeyVault@1
      inputs:
        azureSubscription: 'mdwdo-azsql'
        KeyVaultName: '$(AZURE_KEYVAULT_NAME)'
        SecretsFilter: '*'
    - task: SqlAzureDacpacDeployment@1
      inputs:
        azureSubscription: 'mdwdo-azsql'
        AuthenticationType: 'server'
        ServerName: '$(AZURESQL_FULL_SERVER_NAME)'
        DatabaseName: '$(AZURESQL_DB_NAME)'
        SqlUsername: '$(AZURESQL_SERVER_USERNAME)'
        SqlPassword: '$(AZURESQL-SERVER-KEYVAULT-PASSWORD)'
        deployType: 'DacpacTask'
        DeploymentAction: 'Publish'
        DacpacFile: '$(Pipeline.Workspace)\sql_dacpac\$(SLN_NAME).dacpac'
        IpDetectionMethod: 'AutoDetect'
