# Variables for the test environment
---
variables:
  resourceGroup: MSFT-D-EUS2-RG01
  resourcePrefix: dcmdwtest
  location: southcentralus
  locationFormatted: "South Central US"
  purviewAdmins: "d18ec5f0-05d4-4476-96c4-2eb7d63d75d0"
  azureResourceManagerConnection: SC-${{ variables.resourceGroup }}
  applicationInsightsName: ${{ variables.resourcePrefix }}-ai
  logAnalyticsWorkspaceName: ${{ variables.resourcePrefix }}-log
  virtualNetworkName: ${{ variables.resourcePrefix }}-vnet
  coreInfrastructureSubnetName: internal
  coreInfrastructureSubnetPrefix: "10.0.0.0/24"
  subnetNumber: 1
  subnetNames: ${{ variables.coreInfrastructureSubnetName }}
  subnetPrefixes: ${{ variables.coreInfrastructureSubnetPrefix }}
  keyVaultName: ${{ variables.resourcePrefix }}-kv
  purviewAccountName: ${{ variables.resourcePrefix }}-pv
  dataLakeStorageAccountName: ${{ variables.resourcePrefix }}sa
  dataFactoryName: ${{ variables.resourcePrefix }}-df
  storageContainerName: datalake
  dropzoneStorageContainerName: dropzone
  smtpServer: "smtp.office365.com"
  smtpPort: "587"
  smtpDomain: "outlook.com"
  logSenderFunctionAppName: ${{ variables.resourcePrefix }}lsaf
  emailSenderLogicAppName: ${{ variables.resourcePrefix }}laemail
  emailSenderRecipientAddress: "test@test.com"
  o365ConnectionName: "office365"
  databricksWorkspaceName: ${{ variables.resourcePrefix }}dbricks
