trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

resources:
  pipelines:
  - pipeline: ci
    source: mdw-dbx-mn-ci-pipeline

stages:
- stage: deploy_to_test
  displayName: 'Deploy notebooks'
  variables:
  - group: mdwdo-dbx-mn-test
  jobs:
  - template: ../../devops/templates/jobs/deploy-notebooks-job.yml
    parameters:
      environmentName: 'TEST'
      databricksDomain: '$(databricksDomain)'
      databricksToken: '$(databricksToken)'
      databricksNotebookPath: '$(databricksNotebookPath)'

  - job:
    displayName: 'Run integration tests'
    dependsOn: deploy_notebooks
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      pythonVersion: 3.8
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
        addToPath: true
        architecture: 'x64'
      displayName: 'Use Python Version: $(pythonVersion)'

    - script: |
        pip install nutter
      displayName: 'Install Nutter'

    - script: |
        nutter run $(databricksNotebookPath) $CLUSTER --recursive --junit_report
      displayName: 'Execute Nutter'
      env:
          CLUSTER: '$(databricksClusterId)'
          DATABRICKS_HOST: '$(databricksDomain)'
          DATABRICKS_TOKEN: '$(databricksToken)'

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/test-*.xml'
        testRunTitle: 'Publish Nutter results'
      condition: succeededOrFailed()